library(ggplot2)

# Load data
stats <- read.table("population_stats.tsv", header=TRUE, sep="\t")
fst_stats <- read.table("fst_stats.tsv", header=TRUE, sep="\t")

# Read H-statistics (FST)
fst_stats <- read.table("populations.hstats.tsv", header=T, skip=2)

# Plot nucleotide diversity (π) per population
ggplot(stats, aes(x=pop, y=pi, fill=pop)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title="Nucleotide Diversity (π) per Population", y="π", x="Population")

# Plot FST across the genome
ggplot(fst_stats, aes(x=BP, y=mean_fst)) +
  geom_point(alpha=0.5, size=0.5) +
  facet_wrap(~Chr, scales="free_x") +
  theme_light() +
  labs(title="Genome-wide FST", y="Mean FST", x="Chromosome Position")

# Plot FIS distribution
ggplot(stats, aes(x=FIS, fill=pop)) +
  geom_histogram(position="dodge", bins=30) +
  theme_classic() +
  labs(title="Distribution of FIS", x="FIS", y="Frequency")

##### NOTICE
# This script was generated by an AI language model

##### OTHER
# re-run with --smooth
# use dyplr
